name: Build and Release Go Binaries

on:
    push:
        tags:
        - "v*"

permissions:
    contents: write

jobs:
    build:
        name: Build binaries
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                - goos: linux
                  goarch: amd64
                - goos: linux
                  goarch: arm64
                - goos: darwin
                  goarch: arm64
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
              go-version: "1.23"

        - name: Build binary
          run: |
              mkdir -p dist
              GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} CGO_ENABLED=0 \
                go build -o dist/iptables-parser-${{ matrix.goos }}-${{ matrix.goarch }}

        - name: Upload binaries as artifact
          uses: actions/upload-artifact@v4
          with:
              name: binaries
              path: dist/*

    release:
        name: Create GitHub Release
        needs: build
        runs-on: ubuntu-latest
        steps:
        - name: Download artifacts
          uses: actions/download-artifact@v4
          with:
              name: binaries
              path: dist

        - name: Create Release
          uses: softprops/action-gh-release@v2
          with:
              files: dist/*
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
